In [4]:
import numpy as np


In [10]:
array = np.random.randint(1,21,size=(5,5))
print(array)
#modified array
array[:,2] =1
print(array)

[[ 5  8  2  3 12]
 [ 8 18 13 16 12]
 [ 8  7  1 18  4]
 [ 2  8  4 15 11]
 [12 15  9 15 11]]
[[ 5  8  1  3 12]
 [ 8 18  1 16 12]
 [ 8  7  1 18  4]
 [ 2  8  1 15 11]
 [12 15  1 15 11]]


In [18]:
array = np.arange(1,17).reshape(4,4)
print(array)
np.fill_diagonal(array, 0)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [24]:
array = np.arange(1,37).reshape(6,6)
print(array)

sub_array = array[2:5,1:4]
print(sub_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [30]:
array = np.random.randint(1,21,size=(5,5))
print(array)
sub_array = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print(sub_array)

[[ 3 17 11 13 10]
 [16 16 18  4  4]
 [ 9 15  7  3  5]
 [12 10  5  3  2]
 [13 15 17 14 20]]
[ 3 17 11 13 10 13 15 17 14 20 16  9 12  4  5  2]


In [36]:
array1 = np.random.randint(1,15,size=(3,4))
array2 = np.random.randint(1,18,size=(3,4))

sub_array = (array1+array2)
sub_array1 = (array1-array2)
sub_array2 = (array1*array2)
sub_array3 = (array2/array1)
print(array1)
print(array2)
print(sub_array)
print(sub_array1)
print(sub_array2)
print(sub_array3)

[[ 6 11  7  6]
 [13  9  2 12]
 [ 2 13  7 11]]
[[17  7  9  7]
 [15  3  6  3]
 [13  4 13 14]]
[[23 18 16 13]
 [28 12  8 15]
 [15 17 20 25]]
[[-11   4  -2  -1]
 [ -2   6  -4   9]
 [-11   9  -6  -3]]
[[102  77  63  42]
 [195  27  12  36]
 [ 26  52  91 154]]
[[2.83333333 0.63636364 1.28571429 1.16666667]
 [1.15384615 0.33333333 3.         0.25      ]
 [6.5        0.30769231 1.85714286 1.27272727]]


In [41]:
array = np.arange(1,17).reshape(4,4)
print(array)
sub_sum = np.sum(array,axis=1)
sub_sum1 = np.sum(array,axis=0)
print(sub_sum)
print(sub_sum1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


In [43]:
#4
array = np.random.randint(1,26,size=(5,5))
mean = np.mean(array)
median = np.median(array)
std = np.std(array)
var = np.var(array)
print("space")
print(mean)
print(median)
print(std)
print(var)
print("space")
print(array)

space
10.6
8.0
7.812809993849844
61.04
space
[[ 1  8 10  8  5]
 [22  2 17  6 20]
 [19 14 16 23  9]
 [ 5  3 25  5  1]
 [14  3  5  1 23]]


In [46]:
array = np.arange(1,10).reshape(3,3)
std_dev = np.std(array)
mean = np.mean(array)
normalized_array = (array - mean) / std_dev
print(normalized_array)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
