In [1]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [2]:
arr2 = np.array([1,2,3,4])
arr2.reshape((1,4)) # 1 row 4 columns

array([[1, 2, 3, 4]])

In [3]:

arr3 = np.array([[1,2,3,4,5],[44,45,34,43,49]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [44 45 34 43 49]]
(2, 5)


In [4]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [5]:
#inbuilt function 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
#identity matrix or array
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#numpy vectorized operation
arr12 = np.array([1,2,3,4,5])
arr13= np.array([10,20,30,40,50])
##element wise addition
print("Addition:",arr12+arr13)

##element wise substraction
print("sub:",arr12-arr13)
#u csn perform multiiplication or division

Addition: [11 22 33 44 55]
sub: [ -9 -18 -27 -36 -45]


In [8]:
#universal function
arr = np.array([1,2,3,4,5,6])
#square root
print(np.sqrt(arr))
#exponential 
print(np.exp(arr))
#sine
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [9]:
# slicing and indexing in array 
arr = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [10]:
arr[0:,3:]



array([[4, 5],
       [8, 9]])

In [11]:
#modify array element
arr[0,0] =100
print(arr)

[[100   2   3   4   5]
 [  5   6   7   8   9]]


In [12]:
#stats concept -normalization
##to have change the data of mean = 0 and s.d is 1

data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data 
normalized_data = (data-mean)/std_dev
print("normalized data:",normalized_data)


normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [13]:
#calculate varriance 
data = np.array([1,2,3,4,5])
np.var(data)


np.float64(2.0)

In [14]:
##logical opertaion
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >5) &( data <8)]

array([6, 7])